// Code generated by command: go run sq_l2_f32_avx2.go -out sq_l2_f32_avx2.s -stubs sq_l2_f32_stub_avx2.go. DO NOT EDIT.

#include "textflag.h"

// func SqL2F32AVX2(x []float32, y []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·SqL2F32AVX2(SB), NOSPLIT, $0-52
	MOVQ   x_base+0(FP), AX
	MOVQ   y_base+24(FP), CX
	MOVQ   x_len+8(FP), DX
	VXORPS Y0, Y0, Y0

blockloop:
	CMPQ        DX, $0x00000008
	JL          tail
	VMOVUPS     (AX), Y1
	VMOVUPS     (CX), Y2
	VSUBPS      Y2, Y1, Y1
	VFMADD231PS Y1, Y1, Y0
	ADDQ        $0x00000020, AX
	ADDQ        $0x00000020, CX
	SUBQ        $0x00000008, DX
	JMP         blockloop

tail:
	VXORPS X1, X1, X1

tailloop:
	CMPQ        DX, $0x00000000
	JE          reduce
	VMOVSS      (AX), X2
	SUBSS       (CX), X2
	VFMADD231SS X2, X2, X1
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	DECQ        DX
	JMP         tailloop

reduce:
	VEXTRACTF128 $0x01, Y0, X2
	VADDPS       X0, X2, X0
	VADDPS       X0, X1, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	MOVSS        X0, ret+48(FP)
	RET
