name: CI

on: 
  push:

env:
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: go fmt
      run: go fmt ./...
    - name: go vet
      run: go vet -v ./...
    - name: go test
      run: go test -v 
